### ISSUE TITLE
Setup team Hellofax account

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#303]
With CfA card. Invite the team.

**Comment by RebeccaCoelius** [comment]
@lippytak Is this Health team only? I've been meaning to bug Joseph about
donating credits since gov could be such a huge client for them, and we are
using for Vocatus.

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lippytak** [comment]
Just for health. This is to submit verification documents to counties so we want to keep this siloed from the rest of the org if possible.

**Comment by lippytak** [comment]
Done and invited everyone to the team.
