### ISSUE TITLE
Do stuff for 2nd CDSS deliverable

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#309]
1) `(1) We've had no "scam" texts since that feature shipped` - is this still true?

2) Could you do me a solid and calculate the FTTR for me for balance?

3)DONE Data showing that clients want deposit alerts. Maybe # of checks/time of day to see the bump around midnight as clients wait for deposit? CHARTS!

4) @daguar can you help me find some quotes from clients who have said good things about balance? Can't recall where we put that

5) Nice to have: Choropleth of EBTNM usage by CA county bit.ly/ebtnearme-metrics

6) DOEN What % of Google and/or Bing calfresh/food stamps queries are on mobile?

**Comment by lippytak** [comment]
added (3) above

**Comment by daguar** [comment]
One answer:

(1) No, sadly — but the ones we've had are mostly now due to the Twilio downtime issues :/

**Comment by lippytak** [comment]
Added (4) above

**Comment by lippytak** [comment]
Added (5)

**Comment by lippytak** [comment]
added 6

**Comment by daguar** [comment]
Re (4): some Balance user quotes here https://github.com/codeforamerica/balance/issues/206#issue-47986878

Specifically:
"'And I was like FINALLY, FINALLY! It's so annoying to have to call every time and type in all those numbers. Now I just copy paste copy paste!'"
"'Time is money, you know?'"

Also this doc: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/14Am0UUXrl6jY4H9ZgOnPBwcO0axomLJtnVuvzcyAISk/edit?usp=sharing

**Comment by daguar** [comment]
"very useful, quicker than getting on the phone and have to listen to people speaking, so much easier"
--> she found out about Balance doing her annual renewal and saw something popped up about texting (DG: I'm guessing this is the ad) and didn't know she could go online and check balance either but learned it at that point (but *hasn't gone online because texting is easier*)

^ this was in PA, but I think applies still.
