### ISSUE TITLE
Figure out feedback loop for Q4

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#404]

**Comment by alanjosephwilliams** [comment]
This issue might not be the best place for this brain-dump but I just want to get it down and out as I think through the user research agenda of the week ahead. 

Some stats from November 1st:
- Out of ~1,300 cases, we have "approved"/"denied" outcomes for 457 (35%)
- 40% of those were denied (183 of 457).
- Of those 183 denied, we have denial reasons for 107 (58%)
- The breakdown among denial reasons is basically "a third a third a third" between "ineligible" (primarily due to income), "interviews" and "verifications".
   - 30% ineligible
   - 37% interview
   - 32% verifications

To ratchet up the approval rate in Q4, we need to get a higher-definition view into these denial reasons.  Dave has proposed trying to get something closer to a "real time" understanding of where our clients are in the process and the friction they are encountering. 

For my own head, I want to start to list some of the questions I'd like to have better answers to:
- **What percentage of our clients are ES?**
   - I've heard Jake say 50%, but we don't actually track this in GCF-cases.  I'd be more comfortable having this number as accessible as the numbers above.
- **At what day after application submission are our clients receiving their interview call?**
   - Asking more directly YES or NO whether people have received a call in our FU messages could help us get better view into this pretty quickly.
- **What percentage of our clients answer/miss their initial interview call?**
   - Our denial outcomes include people that have all manners of hellish experiences trying to get an interview. To what extent is missing the first phone call a predictor of being denied for missing your income?
  - When do people learn that they have missed their interview call? How do they learn?
- **What percentage of people who call the office actually reach an eligibility worker who can schedule another interview or conduct one on their first try?**
   - Is there any pattern of time/day/county phone number that consistently leads people to successfully reach a human faster?
- **What percentage of our ES clients (or clients generally) have had their phone number change in the past 3 months**?
   - To what extent should we just be telling ES clients to get their butts into an office if possible?
- **Are their any behaviors around waiting for a call, checking voicemail, unknown numbers, etc. that understanding would allow us to check or anticipate and improve the rates at which people answer county phone calls?**
   - These are deeper ethnographic questions that may or may not reveal important tactics.
- **Are outbound county phone numbers consistent across applicants?**
   - If so, is there anything we could do to prepare for calls from particular numbers?
- **What percentage of people are rewarded a "low" benefit amount—say, $60 or less?**
   - This could serve as a proxy for people that we _should_ be able to screen out.
- **We know that most people learn about CalFresh from friends and family. Do they have their expectations anchored around a benefit amount at the same time?**
- **What kind of expectations to likely ineligible (due to income) applicants have upon submitting a GetCalFresh.org application**
   - If they are not expecting to be approved and applying anyway, we may be more constrained in our ability to improve our approval rate by screening out applicants.


Ok brain dump over for now. Happy to move these questions elsewhere if suggested.

**Comment by lippytak** [comment]
Deprecated
