### ISSUE TITLE
Touch base with Marin re interview problems

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#408]
Per @alanjosephwilliams, lots of clients not getting any contact from the county.

@lippytak — Who would be the best point of contact?

**Comment by daguar** [comment]
@alanjosephwilliams I assigned you, but feel free to re-assign to me if you want.

**Comment by alanjosephwilliams** [comment]
Just to document what we found:
- We had 12 inbound message from clients in Marin last week that had some issue contacting the county via the phone.
- 3 of those were ~30 day cases in which the inability to connect with the county had very likely effected whether or not the person was enrolled.
- 1 of those cases was an ES applicant who was also turned away in person.

Here's what we did:
- We dug into all of our Marin cases from the last 30 days and audited all of their associated support tickets.
- We had one user call which probed the problems more deeply.
- We connected two clients to the Food Bank of San Francisco and Marin.
- We confirmed long wait times by calling ourselves—those wait times are not given to the caller.
- We determined that sending clients to the ACA call center for a warm referral the county was not a feasible option
- We raised the pattern with our partners at the food bank, who confirmed that the issue was known and being discussed/addressed.

![image](https://cloud.githubusercontent.com/assets/2983464/10871454/3ca39612-809c-11e5-9c4e-5be3d0706281.png)
